# Generated by Django 6.0.3 on 2026-03-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.creativefabrica.com/wp-content/uploads/2021/04/06/Food-Icon-with-Pink-Cutlery-Plate-Graphics-10479612-1.jpg', max_length=500),
        ),
    ]
